### ISSUE TITLE
Suggestion: End-of-Game Screen Item Tooltip

### ISSUE THREAD

**Issue by TheVanadium** [zachpmanson/minecraftle#41]
The old version of Minecraftle before the React overhaul told the user what the item was, but this could be a compact alternative. It would be nice if there was a tooltip here to let the user know the name of the correct item, especially if they don't recognize it. 

<img src="https://github.com/zachpmanson/minecraftle/assets/53013571/a205b2d0-a732-426c-a0c2-96b739473e82" width="200" height="280">

It would also be interesting, although it would possibly take considerable space, to show the correct crafting recipe on the end-of-game screen as well.

**Comment by zachpmanson** [comment]
I reckon that we should just readd the item label beneath the picture of the solution
