### ISSUE TITLE
Item appears in target slot on mousedown but leaves cursor on mouseup

### ISSUE THREAD

**Issue by zachpmanson** [zachpmanson/minecraftle#44]

**Comment by TheVanadium** [comment]
Is this a bug? It made sense that dropping the item in the slot would deposit the item, just like in Minecraft; it's an item deposit, not a paintbrush. If they still need the item, they can just pick it back up from the slot where they left off.

Maybe I'm misunderstanding. What are the steps for recreation?

**Comment by zachpmanson** [comment]
After further investigation this is expected behaviour
