### ISSUE TITLE
Suggestion: Winrate Statistics Rounding

### ISSUE THREAD

**Issue by TheVanadium** [zachpmanson/minecraftle#45]
I think having 16 significant digits is a little overkill in the statistics menu. I think this should be trimmed down to two decimals places. If nothing else, it looks pretty out of place with all the other whole numbers.
![image](https://github.com/zachpmanson/minecraftle/assets/53013571/1267f28d-ca87-4f96-98af-bf3ae9ed208b)

**Comment by zachpmanson** [comment]
Yeah should round this down to whole numbers
