### ISSUE TITLE
Music Icon Missing on Website

### ISSUE THREAD

**Issue by TheVanadium** [zachpmanson/minecraftle#46]
![image](https://github.com/zachpmanson/minecraftle/assets/53013571/28539e6d-c0f2-44ba-83a9-9f31ea328be1)
I just noticed this; I don't know if it was like this the other day. This mismatch seems pretty serious though.

**Comment by zachpmanson** [comment]
I have disabled the music button intentionally as it was actually taking up quite a lot of bandwidth since moving to being hosted on vercel.  I'm only on the vercel free tier so i'm limited to 100GB, that music file used up 40GB alone over the last few weeks.

**Comment by TheVanadium** [comment]
wontfix label might be good here, unless there are plans to find a suitably low-bandwith music-playing method
