### ISSUE TITLE
Air is a block.

### ISSUE THREAD

**Issue by The4codeblocks** [zachpmanson/minecraftle#51]
So why can't you color air spaces to know if there's nothing there, or if the nothing is elsewhere?

**Comment by TheVanadium** [comment]
It was my understanding that it would make the game too easy; crafting recipes have pretty unique shapes. Additionally, this is supposed to be analogous to Wordle, where there are no empty boxes, and there wasn't really a protocol for that.

**Comment by The4codeblocks** [comment]
> analogous to Wordle

That's exactly why I suggested this
Wordle doesn't have characters that are always gray

**Comment by zachpmanson** [comment]
Yes this would make the game way to easy, many solutions are given away by their shape.
